name: CI/CD

on:
  push:
    branches: 
      - main
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Define ENV VARS
        id: define_env
        run:  echo "::set-output name=github-sha-short::$(echo $GITHUB_SHA | cut -c 1-7)"
      - name: Openfaas Test
        run: |
          curl -sSL https://cli.openfaas.com | sudo sh 
          faas login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} -g ${{ secrets.OPENFAAS_GATEWAY }}
          echo | faas invoke nodeinfo -g ${{ secrets.OPENFAAS_GATEWAY }}
      -
        name: Login to OpenFaaS Gateway
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} \
                      -g ${{ secrets.OPENFAAS_GATEWAY }}
      -
        name: Test Openfaas connection
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: invoke nodeinfo                             
      -
        name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template store pull csharp-httprequest
      - 
        name: Run shrinkwrap build
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f csharptestfunction.yml --shrinkwrap

      -
        name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build and Push the OpenFaaS function
        uses: docker/build-push-action@v2
        with:
          context: ./build/csharptestfunction/
          file: ./build/csharptestfunction/Dockerfile
          push: true
          tags: sopor10/csharptestfunction:latest-${{ steps.define_env.outputs.github-sha-short }}
      - 
        name: Deploy the function
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: deploy -f csharptestfunction.yml --tag sha  
