name: CI/CD

on:
  push:
    paths: 
      - 'elmtest.yml'
      - '.github/workflows/elmtest.yml'
      - 'elmtest/**'
env: 
  FUNCTION : 'elmtest'      
jobs:
  elmtest-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Define ENV VARS
        id: define_env
        run:  echo "::set-output name=github-sha-short::$(echo $GITHUB_SHA | cut -c 1-7)"
      -
        name: Login to OpenFaaS Gateway
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} \
                      -g ${{ secrets.OPENFAAS_GATEWAY }}
      -
        name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template pull https://github.com/Sopor10/Openfaas-Elm-Template.git#main
      -
        name: Folder Structure
        id: look
        run: ls -a
      - 
        name: Run shrinkwrap build
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f ${{ env.FUNCTION }}.yml --shrinkwrap

      -
        name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build and Push the OpenFaaS function
        uses: docker/build-push-action@v2
        with:
          context: ./build/${{ env.FUNCTION }}/
          file: ./build/${{ env.FUNCTION }}/Dockerfile
          push: true
          tags: sopor10/${{ env.FUNCTION }}:latest-${{ steps.define_env.outputs.github-sha-short }}
      - 
        name: Deploy the function
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: deploy -f ${{ env.FUNCTION }}.yml --tag sha -g ${{ secrets.OPENFAAS_GATEWAY }}
